"""Writer Agent — generates content with RAG style constraints"""


class WriterAgent:
    """Generates article content following an outline, using RAG context
    for style guidance and platform-specific formatting."""

    def __init__(self):
        self.name = "writer"

    async def run(self, project_context: dict, outline: dict,
                  platform: str, rag_context: list[str], word_count: int) -> dict:
        """Generate article sections from an outline."""
        title = outline.get("title", "Untitled")
        outline_items = outline.get("outline", [])
        writing_style = project_context.get("writing_style", "neutral")

        sections = []
        for item in outline_items:
            content = self._generate_section_content(
                heading=item,
                writing_style=writing_style,
                platform=platform,
                rag_context=rag_context,
                word_count=word_count // max(len(outline_items), 1)
            )
            sections.append({
                "heading": item,
                "content": content,
                "rag_ref": rag_context[0] if rag_context else None
            })

        return {
            "title": title,
            "sections": sections,
            "platform": platform,
            "metadata": {"word_count": word_count, "writing_style": writing_style}
        }

    def _generate_section_content(self, heading: str, writing_style: str,
                                   platform: str, rag_context: list[str],
                                   word_count: int) -> str:
        """Generate content for a single section. In production, this calls an LLM."""
        prefix = f"[{writing_style}] " if writing_style else ""
        rag_hint = f" Using reference: {rag_context[0][:50]}..." if rag_context else ""
        return f"{prefix}Content for '{heading}' on {platform}.{rag_hint} " \
               f"(~{word_count} words placeholder - real content generated by LLM)"
